# ─────────────────────────────────────────────────────────────
# Cerebro — multi-stage build
# Builds shared types + React UI, then the NestJS server, and
# ships a single runtime image that serves both.
#
# Base is Debian (bookworm-slim), NOT Alpine: signal-cli's native
# libsignal_jni is built for glibc and cannot resolve glibc-only symbols
# (e.g. __register_atfork) under Alpine's musl, even with gcompat. Debian
# also keeps Prisma's engine target (glibc) consistent across build & runtime.
# ─────────────────────────────────────────────────────────────

# 1) Install all workspace deps once (cached)
FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
COPY packages/shared/package.json ./packages/shared/
COPY apps/server/package.json ./apps/server/
COPY apps/web/package.json ./apps/web/
RUN npm install

# 2) Build shared, web, and server
FROM node:22-bookworm-slim AS build
WORKDIR /app
ARG GIT_SHA=dev
ENV VITE_GIT_SHA=$GIT_SHA
ENV GIT_SHA=$GIT_SHA
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build --workspace @cerebro/shared \
 && npm run build --workspace @cerebro/web \
 && npm run prisma:generate --workspace @cerebro/server \
 && npm run build --workspace @cerebro/server
# Place built UI where the server serves static files from.
RUN mkdir -p apps/server/public && cp -r apps/web/dist/* apps/server/public/

# 2b) Build the Fabric agent binaries (Go). Cross-compiled, static (CGO off), so
# they run on any Linux/Windows host. Served by the server at
# /api/fabric/agent/binary (FABRIC_AGENT_DIST_DIR=/app/agent-dist). go.sum is
# generated by `go mod download` if not committed. See docs/fabric-remote-access.md.
FROM golang:1.22-bookworm AS agent-build
WORKDIR /agent
COPY agent/go.mod agent/go.sum* ./
RUN go mod download
COPY agent/ ./
RUN CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o /agent-dist/cerebro-agent-linux-amd64 . \
 && CGO_ENABLED=0 GOOS=linux   GOARCH=arm64 go build -trimpath -ldflags "-s -w" -o /agent-dist/cerebro-agent-linux-arm64 . \
 && CGO_ENABLED=0 GOOS=darwin  GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o /agent-dist/cerebro-agent-darwin-amd64 . \
 && CGO_ENABLED=0 GOOS=darwin  GOARCH=arm64 go build -trimpath -ldflags "-s -w" -o /agent-dist/cerebro-agent-darwin-arm64 . \
 && CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o /agent-dist/cerebro-agent-windows-amd64.exe .

# 2c) Build the `cerebro` CLI binaries (Go). Served at /api/fabric/cli/binary
# (FABRIC_CLI_DIST_DIR=/app/cli-dist). See docs/fabric-remote-access.md (Phase 5).
FROM golang:1.22-bookworm AS cli-build
WORKDIR /cli
COPY cli/go.mod cli/go.sum* ./
RUN go mod download
COPY cli/ ./
RUN CGO_ENABLED=0 GOOS=linux   GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o /cli-dist/cerebro-linux-amd64 . \
 && CGO_ENABLED=0 GOOS=linux   GOARCH=arm64 go build -trimpath -ldflags "-s -w" -o /cli-dist/cerebro-linux-arm64 . \
 && CGO_ENABLED=0 GOOS=darwin  GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o /cli-dist/cerebro-darwin-amd64 . \
 && CGO_ENABLED=0 GOOS=darwin  GOARCH=arm64 go build -trimpath -ldflags "-s -w" -o /cli-dist/cerebro-darwin-arm64 . \
 && CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -trimpath -ldflags "-s -w" -o /cli-dist/cerebro-windows-amd64.exe .

# 3) Runtime — only production deps + built output
FROM node:22-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
ARG GIT_SHA=dev
ENV GIT_SHA=$GIT_SHA
# signal-cli version to bundle (https://github.com/AsamK/signal-cli/releases).
# Signal's servers reject clients that are too old (connection closed on link),
# so keep this reasonably current.
ARG SIGNAL_CLI_VERSION=0.14.7
# Java for signal-cli. 0.14.x requires JRE 25. A newer JRE still runs older
# class files, so overshoot rather than risk UnsupportedClassVersionError. We
# fetch Adoptium's portable generic-linux JRE (conservative glibc baseline), so
# it runs on this Debian base regardless of the JRE's own build distro.
ARG JAVA_VERSION=25

# openssl → Prisma engine; restic → Backblaze B2 backup connector; iputils-ping →
# the uptime monitor's Ping probe (needs CAP_NET_RAW on the container, see compose);
# git → App Replicator clones a repo to introspect its compose file (docs/app-replicator.md);
# postgresql-client-16 → pg_dump/psql for the full system backup & restore. Pulled from the
# official PGDG repo (bookworm ships only client 15, which can't dump our postgres:16 server).
# See docs/system-backup.md. Then fetch a Temurin JRE (arch-matched) + signal-cli onto PATH.
RUN apt-get update \
 && apt-get install -y --no-install-recommends openssl openssh-client restic ca-certificates wget gnupg iputils-ping git \
 && install -d /usr/share/keyrings \
 && wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/pgdg.gpg \
 && echo "deb [signed-by=/usr/share/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
 && apt-get update \
 && apt-get install -y --no-install-recommends postgresql-client-16 \
 && rm -rf /var/lib/apt/lists/* \
 && ARCH="$(dpkg --print-architecture)" \
 && case "$ARCH" in amd64) JARCH=x64;; arm64) JARCH=aarch64;; *) JARCH="$ARCH";; esac \
 && wget -qO /tmp/jre.tar.gz \
      "https://api.adoptium.net/v3/binary/latest/${JAVA_VERSION}/ga/linux/${JARCH}/jre/hotspot/normal/eclipse" \
 && mkdir -p /opt/java \
 && tar -xzf /tmp/jre.tar.gz -C /opt/java --strip-components=1 \
 && rm /tmp/jre.tar.gz \
 && wget -qO /tmp/signal-cli.tar.gz \
      "https://github.com/AsamK/signal-cli/releases/download/v${SIGNAL_CLI_VERSION}/signal-cli-${SIGNAL_CLI_VERSION}.tar.gz" \
 && tar -xzf /tmp/signal-cli.tar.gz -C /opt \
 && ln -sf "/opt/signal-cli-${SIGNAL_CLI_VERSION}/bin/signal-cli" /usr/local/bin/signal-cli \
 && rm /tmp/signal-cli.tar.gz
ENV JAVA_HOME=/opt/java
ENV PATH="/opt/java/bin:${PATH}"
# signal-cli account state (keys, registration) lives here — mount a volume.
# NOTE: our own var, passed to signal-cli as --data-dir. Do NOT name it
# SIGNAL_CLI_CONFIG — that's signal-cli's config *file* path in 0.14+.
ENV SIGNAL_CLI_DATA_DIR=/data/signal
RUN mkdir -p /data/signal

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/apps/server/package.json ./apps/server/package.json
COPY --from=build /app/apps/server/dist ./apps/server/dist
COPY --from=build /app/apps/server/public ./apps/server/public
COPY --from=build /app/apps/server/prisma ./apps/server/prisma
COPY --from=build /app/packages/shared/dist ./packages/shared/dist
COPY --from=build /app/packages/shared/package.json ./packages/shared/package.json
# Fabric agent binaries, served to installers by /api/fabric/agent/binary.
ENV FABRIC_AGENT_DIST_DIR=/app/agent-dist
COPY --from=agent-build /agent-dist ./agent-dist
# `cerebro` CLI binaries, served by /api/fabric/cli/binary.
ENV FABRIC_CLI_DIST_DIR=/app/cli-dist
COPY --from=cli-build /cli-dist ./cli-dist
COPY docker/entrypoint.sh ./docker/entrypoint.sh
RUN chmod +x ./docker/entrypoint.sh
# Remote Browser build context — the app auto-builds this image on first use
# (via the Docker socket), so no manual `docker build` step is needed. The env var
# points the app straight at it (cwd is apps/server, not /app).
COPY docker/remote-browser ./docker/remote-browser
ENV REMOTE_BROWSER_BUILD_CONTEXT=/app/docker/remote-browser
EXPOSE 3000
# entrypoint runs prisma migrate deploy + seed, then starts the server
ENTRYPOINT ["./docker/entrypoint.sh"]
